[package]
name = "arch-check-repro"
version = "0.1.0"
authors = ["orhun <orhun@archlinux.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
